version: '3.1'
services:
  db:
    image: "postgres:14.4"
    container_name: "advisorex-dev"
    restart: always
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
