use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# AdvisorWeb.Endpoint.load_from_system_env/1 dynamically.
# Any dynamic configuration should be moved to such function.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :advisor, AdvisorWeb.Endpoint,
  load_from_system_env: true,
  url: [scheme: "https", host: "advisorex-demo.herokuapp.com", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :advisor, Advisor.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "15"),
  ssl: true

config :ueberauth, Ueberauth,
  base_path: "/auth",
  providers: [
    google: {Local.Strategy, [request_path: "/auth/login", callback_path: "/auth/callback"]}
  ]

config :advisor, FeatureToggle, emails: true

config :advisor, Advisor.Notifications.Email.Mailer, adapter: Bamboo.LocalAdapter
